import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Inter } from 'next/font/google';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

const inter = Inter({ subsets: ['latin'] });

import { Box, Divider, Typography } from '@mui/material';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <Box as='main' padding={3}>
            <Box as='header' display='flex' justifyContent='space-between'>
              <Box
                display='flex'
                minHeight='50px'
                minWidth='120px'
                borderRight={1}
                borderBottom={1}
                borderColor='ActiveBorder'
              ></Box>
              <Box
                display='flex'
                flexGrow={3}
                borderBottom={1}
                justifyContent='center'
                borderColor='ActiveBorder'
              ></Box>
              <Box
                display='flex'
                minHeight='50px'
                minWidth='120px'
                borderLeft={1}
                borderBottom={1}
                borderColor='ActiveBorder'
              />
            </Box>

            <Box display='flex' justifyContent='space-between' as='main'>
              <Box
                display='flex'
                minHeight='50px'
                minWidth='120px'
                borderRight={1}
                borderColor='ActiveBorder'
              />

              <Box display='flex' flexGrow={3} borderColor='ActiveBorder' minHeight='50vh'>
                {children}
              </Box>

              <Box
                display='flex'
                minHeight='50px'
                minWidth='120px'
                borderLeft={1}
                borderColor='ActiveBorder'
              />
            </Box>

            <Box display='flex' justifyContent='space-between' as='footer'>
              <Box
                display='flex'
                minHeight='50px'
                minWidth='120px'
                borderTop={1}
                borderRight={1}
                borderColor='ActiveBorder'
              />
              <Box display='flex' flexGrow={3} borderTop={1} borderColor='ActiveBorder' />
              <Box
                display='flex'
                minHeight='50px'
                minWidth='120px'
                borderLeft={1}
                borderTop={1}
                borderColor='ActiveBorder'
              />
            </Box>
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
