import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Box, Button, Grid, Paper, Stack, Typography } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import { Inter } from 'next/font/google';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Blog Application Development',
  description: 'Generated by create next app',
};

const border = '1px solid GrayText';

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className} style={{ margin: '0' }}>
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <ThemeProvider theme={theme}>
            <Grid as={Paper} square container sx={{ '& .MuiGrid-item': { padding: '30px' } }} padding='5px'>
              <Grid
                as={Paper}
                square
                item
                lg={3}
                borderColor='ActiveBorder'
                sx={{ borderRight: border, borderBottom: border }}
              />
              <Grid as={Paper} square item lg={6} borderColor='ActiveBorder' sx={{ borderBottom: border }}>
                <Stack direction='row' justifyContent='space-between' alignItems='center'>
                  <Typography
                    fontSize='26px'
                    fontWeight='600'
                    textTransform='uppercase'
                    color='primary'
                    letterSpacing={1}
                  >
                    Blog Application Development
                  </Typography>
                  <Link href='/' passHref>
                    <Button variant='outlined' color='secondary'>
                      Home
                    </Button>
                  </Link>
                </Stack>
              </Grid>
              <Grid
                as={Paper}
                square
                item
                lg={3}
                borderColor='ActiveBorder'
                sx={{ borderLeft: border, borderBottom: border }}
              />

              <Grid as={Paper} square item lg={3} borderColor='ActiveBorder' borderRight={border} />

              <Grid as={Paper} square item lg={6} borderColor='ActiveBorder'>
                {children}
              </Grid>
              <Grid as={Paper} square item lg={3} borderColor='ActiveBorder' borderLeft={border} />

              <Grid as={Paper} borderColor='ActiveBorder' square item lg={3} borderTop={border} borderRight={border} />
              <Grid borderColor='ActiveBorder' as={Paper} square item lg={6} borderTop={border}></Grid>
              <Grid borderColor='ActiveBorder' as={Paper} square item lg={3} borderTop={border} borderLeft={border} />
            </Grid>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
